version: "3.9"
services:
  server:
    container_name: Server
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      MODE: server
    ports:
      - "2205:2205"
